# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Contribution Survey
on:
  workflow_dispatch

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Today's date
        run: echo "TODAY=$(date '+ %A, %d %B, %Y')" >> $GITHUB_ENV
      - name: Month
        run: echo "MONTH=$(TZ=CST+24 date +%B)" >> $GITHUB_ENV
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "stephen-rowan"
          labels: "Contribution Survey"
          title: SecretDecks-ContributionSurvey - ${{ env.MONTH }}
          body: |
            SecretDecks-Contribution Survey - opened on - ${{ env.TODAY }}
            
            * Previous Survey - https://github.com/Ek-phrasis/Sandbox/issues/{{ previousIssueNumber }}
                    
            ## Autonomous Creator Organisation (ACO) - Contribution-Survey

            ## General Information

            This provides an overall summary or context of a member, when they became involved and how many days they have worked.
            This could be supplemented with a contribution vote by peers to capture the more intangible contribution a member has made. 

            - [ ] Date joined ACO - [Month/Day/Year]
            - [ ] Days / Hours worked overall - [00 Days/Hours]
            - [ ] Cost of contribution (from member perspective) - [$ 0]
            - [ ] Contribution vote
     
            ## Development

            Each work area will be divided into appropriate categories (e.g. Code, UX etc.) and be accompanied with an "Outputs" section where members can record what they have produced, built, documented etc.

            - [ ] Code
            - [ ] UX
            - [ ] Test
            - [ ] Support

          pinned: false
          close-previous: true
          linked-comments: true          
                   
        env:           
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
