name: open-issue
  # You may pin to the exact commit or the version.
  # uses: rishabhgupta/git-action-issue@05095a071ec1fa279fff18873b8de34366d38790
uses: rishabhgupta/git-action-issue@v2.0.0
  with:
    # Github Token
    token: 
    # Issue Title
    title: 
    # Issue Body
    body: # optional
    # Issue Assignee
    assignees: # optional
