# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Core Swarm Activities
on:
  schedule:
    - cron: 40 21 * * *

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Today's date
        run: echo "TODAY=$(date '+%Y-%B-%A')" >> $GITHUB_ENV
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "stephen-rowan"
          labels: "Weekly Tasks"
          title: "Core Swarm Activities"
          body: |
            ### Core Swarm Activities ${{ env.TODAY }}

            - [ ] DominikTilman
            - [ ] FelixWeber
            - [ ] Filip
            - [ ] Tevo 
                    
            ### Today's Activities
            
            - [Today's Activities](https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/143           )
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
