name : testing
on : push

jobs:
  build-and-run:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build code
        run: pwd && whoami && ls -l
