# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Townhall-slides
on :
  workflow_dispatch:
  #schedule:
  #  - cron: 0 0 * * 3
    
jobs:
  create_issue:
    name: Create Town Hall slides
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Today's date
        run: echo "TODAY=$(date -d '7 days' '+ %A, %dth %B, %Y')" >> $GITHUB_ENV
      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        with:
          token: $GITHUB_TOKEN
          assignees: "Andre-Diamond"
          labels: "slides"
          title: Town Hall Slides - ${{ env.TODAY }}
          body: |
            ### Townhall slides - ${{ env.TODAY }}
            
            * Previous Town Hall - https://github.com//Ek-phrasis/Sandbox/issues/{{ previousIssueNumber }}
            * CC Admin meeting - 
            
            - [ ] Prepare Town Hall slides for Wednesday
            
          project: 2  # The project-number from organization project https://github.com/orgs/org/projects/project-number
          column: In progress
          pinned: false
          close-previous: true
          linked-comments: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
